# Generated by Django 3.1 on 2020-08-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AiInfoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aistudent',
            old_name='intro',
            new_name='intro_text',
        ),
    ]
